import Head from 'next/head'


export default function Home() {
  return (
    <div className=''>
      <Head>
        <title>Google clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

     <h1>Hello world</h1>


    </div>
  )
}
